### ISSUE TITLE
Change request /order/details to get "id_product"

### ISSUE THREAD

**Issue by ThomasMoulins** [FAST-SUSHI-NEXTECH/API#11]
J'ai besoin de modifier la requete qui me permet de récupérer le contenu d'une commande en rajoutant l'id des entrées/plats/desserts

POST order/details

exemple du Request body :
{
  "id_order": 160
}

exemple du Response body :
[
  {
    "id_product": 202,
    "type_product": "dessert",
    "product_name": "Moelleux Chocolat",
    "price": 12.99,
    "quantity": null
  }
]

**Comment by StopThatTalace** [comment]
done here's the new response body: 

![2024-02-06_17h45_38](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/bd5d15e4-dbd4-48b8-8e8b-830f8ec68185)
