### ISSUE TITLE
Add /product/update

### ISSUE THREAD

**Issue by ValLilian** [FAST-SUSHI-NEXTECH/API#16]
Je souhaiterai une requête pour modifié un produit (changer la description ou le prix par exemple)

Avec un body de ce genre:
{
    "id_product": 1,
    "type_product": "base",
    "product_name": "saumon",
    "description": "Description1",
    "price": 10.99,
    "quantity": null
  }

**Comment by StopThatTalace** [comment]
update : type_product, product_name, description, price and quantity

**Comment by StopThatTalace** [comment]
Done! c'est up
