### ISSUE TITLE
Add /product/create

### ISSUE THREAD

**Issue by ValLilian** [FAST-SUSHI-NEXTECH/API#17]
Je souhaiterai pourvoir ajouter un produit avec une requête.

Le body serait:
{
    "type_product": "base",
    "product_name": "saumon",
    "description": "Description1",
    "price": 10.99,
    "quantity": null
  }

(Ps: il faudrai donc mettre l'id en autoincrement)

**Comment by StopThatTalace** [comment]
l'id est déjà en auto increment ! J'ai juste mis une règle qui assigne les id par centaines mais sinon c'est bien auto incrementé

**Comment by StopThatTalace** [comment]
done! for next release.
![2024-02-20_09h23_30](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/904ad162-3954-4727-8461-41e65447b6fb)

**Comment by StopThatTalace** [comment]
be careful quantity can't be Null
