### ISSUE TITLE
Add /user/staff/id

### ISSUE THREAD

**Issue by ValLilian** [FAST-SUSHI-NEXTECH/API#22]
Je voudrais récuperer les informations des staffs sous le même format que les clients

<img width="1070" alt="image" src="https://github.com/FAST-SUSHI-NEXTECH/API/assets/124347451/32d8b83e-f1ba-4804-8940-bb91af14db98">

but permission lvl 2 / 3

**Comment by StopThatTalace** [comment]
done! update /user/client/id to /user/id to retrieve any user with any perm!
