### ISSUE TITLE
Add /order/total

### ISSUE THREAD

**Issue by ValLilian** [FAST-SUSHI-NEXTECH/API#23]
Je souhaiterai avoir le montant total de toutes les commandes avec le stade 3

{total_count: 999.9$}

**Comment by StopThatTalace** [comment]
Done ! Post request by state
![2024-03-05_08h52_14](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/919273e9-5d92-451d-9904-7f0a6cbf532a)
