### ISSUE TITLE
Update /order/id/user

### ISSUE THREAD

**Issue by ValLilian** [FAST-SUSHI-NEXTECH/API#24]
Je souhaite modifié cette requête pour pouvoir l'utiliser en admin, donc rajouter l'id du user en paramètre 

<img width="1071" alt="image" src="https://github.com/FAST-SUSHI-NEXTECH/API/assets/124347451/ccda2607-b780-44f5-9163-7766e2e98a53">

{
  "id_user": 0
}

**Comment by StopThatTalace** [comment]
Already existing !!! Please check up before asking for new request !!! 
![2024-03-05_09h07_40](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/f8e3a2fa-f49c-46b9-8e3b-9d7b70140d79)
