### ISSUE TITLE
Update the picker of an order

### ISSUE THREAD

**Issue by ThomasMoulins** [FAST-SUSHI-NEXTECH/API#4]
J'ai besoin de mettre à jour le préparateur de la commande avec une requête

PUT /order/picker/update

exemple du Request body :
{
  "id_picker": 0,
  "id_order": 0
}

**Comment by StopThatTalace** [comment]
Done, has asked it take these parameters!
![2024-01-26_11h09_08](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/3fee76b4-7ea6-49ed-891d-27927d494877)
![2024-01-26_11h09_40](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/000da637-a3ff-492a-9312-06578b976f01)
