### ISSUE TITLE
Get the picker id with username

### ISSUE THREAD

**Issue by ThomasMoulins** [FAST-SUSHI-NEXTECH/API#6]
J'ai besoin de récupérer l'id préparateur en lui fournissant l'username du préparateur

POST /user/picker/username

exemple du Request body :
{
  "username": "randomUser"
}

**Comment by StopThatTalace** [comment]
Done ! Username for parameter, picker token and that's all 🐧
![2024-01-26_11h24_53](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/cff11986-237d-46b1-a87b-c5369e89858a)
![2024-01-26_11h25_12](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/e13e06e8-e80b-46d2-af2a-8cc2c3019438)
