### ISSUE TITLE
Create - Get Leaderboard

### ISSUE THREAD

**Issue by ValLilian** [FAST-SUSHI-NEXTECH/API#7]
J'ai besoin de récupérer le leaderboard des commandes par préparateur

Get /user/picker/leaderboard

Pas de body, retour de la requête suivante:

SELECT customer_order.id_picker, count(id_order) as nbr_cmd, user.last_name, user.first_name
FROM customer_order
INNER JOIN order_picker ON customer_order.id_picker = order_picker.id_picker
INNER JOIN user ON order_picker.id_user = user.id_user
GROUP BY id_picker
ORDER BY nbr_cmd DESC
LIMIT 3

**Comment by StopThatTalace** [comment]
done! Have fun
⚠️ needs picker token to make it

![2024-02-03_10h00_38](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/bee14617-fe88-4dd4-8747-6e4f9318d3be)
![2024-02-03_10h00_44](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/00aab493-7425-493a-af74-930807f07730)
