### ISSUE TITLE
UPDATE  CLIENT pour TEAM DESKTOP

### ISSUE THREAD

**Issue by buggluck** [FAST-SUSHI-NEXTECH/API#8]
j'ai besoin d'update un client 

voici les champs que je souhaite modifié : 

"last_name": "string",
  "first_name": "string", 
  "username": "string",
  "password": "string",
  "email": "string",
  "tel": "string"

**Comment by StopThatTalace** [comment]
have fun! 
⚠️The user_id parameter is mandatory

![2024-02-03_09h23_02](https://github.com/FAST-SUSHI-NEXTECH/API/assets/117742366/2f523cce-3ce8-412a-9c10-eea0dda32140)
